services:
  app:
    container_name: api
    image: ghcr.io/danfred360/what_did_i_sign_up_for-api:latest
    environment:
      VECTORDB_HOST: vectordb
      VECTORDB_PORT: 5432
      INPUT_FILES_DIRECTORY: /code/input_files
    env_file:
      - app.env
    ports:
      - 80:80
    volumes:
      - ./input_files:/code/input_files

  vectordb:
    container_name: vectordb
    image: ghcr.io/danfred360/what_did_i_sign_up_for-vectordb:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - vectordb.env
    volumes:
      - ./data:/var/lib/postgresql/data