version: '3.7'

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=*/5 * * * * # poll every 5 seconds
      - WATCHTOWER_CLEANUP=true

  traefik:
    image: traefik:v2.4
    container_name: reverse-proxy
    restart: always
    env_file:
      - traefik.env
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.myresolver.acme.email=dannyfrederick360@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

  app:
    container_name: app
    image: ghcr.io/danfred360/what_did_i_sign_up_for-app:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`npole.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  api:
    container_name: api
    image: ghcr.io/danfred360/what_did_i_sign_up_for-api:latest
    restart: always
    environment:
      VECTORDB_HOST: vectordb
      VECTORDB_PORT: 5432
      INPUT_FILES_DIRECTORY: /code/input_files
    env_file:
      - api.env
    volumes:
      - ./input_files:/code/input_files
      - ./logs/api:/var/log/what-did-i-sign-up-for
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.npole.org`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.services.api.loadbalancer.server.port=80"

  auth:
    container_name: auth
    image: ghcr.io/danfred360/what_did_i_sign_up_for-auth:latest
    restart: always
    env_file:
      - auth.env
    volumes:
      - ./logs/api:/var/log/what-did-i-sign-up-for
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.npole.org`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=80"


  vectordb:
    container_name: vectordb
    image: ghcr.io/danfred360/what_did_i_sign_up_for-vectordb:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - vectordb.env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./logs/vectordb:/var/log/postgresql
