version: '3.8'

services:
  vectordb:
    container_name: vectordb
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    env_file:
      - vectordb.env
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data