import { StyleSheet, Dimensions, Platform } from 'react-native';

const mainStyles = StyleSheet.create({
    parent_container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#7b4397',
        padding: Platform.select({
            ios: 40,
            android: 20,
            web: 20,
            default: 20,
        }),
    },
    fixed_container: {
        maxHeight: 150,
        overflow: 'hidden',
        justifyContent: 'flex-start',
    },
    expandable_container: {
        maxHeight: 'auto',
    },
    form_area: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#D1C4E9',
        borderRadius: 20,
        shadowColor: '#52206b',
        shadowOffset: {
            width: 10,
            height: 10,
        },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        margin: Platform.select({
            ios: 20,
            android: 20,
            web: 20,
            default: 20,
        }),
        width: Platform.select({
            ios: 350,
            android: 325,
            web: 350,
            default: 350,
        }),
    },
    settings_area: {
        position: 'absolute',
        left: 20,
        top: 0,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 20,
        shadowColor: '#52206b',
        shadowOffset: {
            width: 30,
            height: 35,
        },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        width: 100,
        margin: Platform.select({
            ios: 40,
            android: 40,
            web: 40,
            default: 20,
        }),
    },
    item: {
        backgroundColor: '#E0E0E0',
        borderRadius: 20,
        padding: 10,
        margin: 10,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        width: Platform.select({
            ios: 290,
            android: 290,
            web: 290,
            default: 290,
        }),
    },
    title: {
        color: '#7b4397',
        fontWeight: '900',
        fontSize: 24,
        marginTop: 20,
    },
    sub_title: {
        fontWeight: '600',
        marginVertical: 5,
    },
    text: {
        fontSize: 16,
        color: '#333',
    },
    paragraph: {
        margin: 20,
    },
    link: {
        fontWeight: '800',
    },
    form_group: {
        flexDirection: 'column',
        margin: 20,
        alignItems: 'center',
        justifyContent: 'center',
        width: Platform.select({
            ios: 300,
            android: 300,
            web: 300,
            default: 300,
        }),
    }, 
    form_group_horizontal: {
        flexDirection: 'row',
        margin: 20,
        alignItems: 'center',
        justifyContent: 'flex-start',
        width: Platform.select({
            ios: 300,
            android: 300,
            web: 300,
            default: 300,
        }),
    },
    form_group_horizontal_centered: {
        flexDirection: 'row',
        margin: 20,
        alignItems: 'center',
        justifyContent: 'center',
        width: Platform.select({
            ios: 300,
            android: 300,
            web: 300,
            default: 300,
        }),
    },
    form_style: {
        borderWidth: 2,
        borderColor: '#000',
        shadowColor: '#000',
        shadowOffset: {
            width: 3,
            height: 4,
        },
        shadowOpacity: 1,
        padding: 12,
        borderRadius: 4,
        fontSize: 15,
        backgroundColor: '#fff',
        width: Platform.select({
            ios: 200,
            android: 200,
            web: 200,
            default: 200,
        }),
        height: 50,
    },
    form_style_focused: {
        translateY: 4,
        shadowOffset: {
            width: 1,
            height: 2,
        },
    },
    btn: {
        padding: 15,
        marginVertical: 30,
        marginHorizontal: 10,
        minWidth: 50,
        fontSize: 15,
        backgroundColor: 'gray', // '#fff',
        borderRadius: 30,
        fontWeight: '800',
        shadowColor: '#000',
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: {
            width: 5,
            height: 5,
        },
        shadowOpacity: 1,
    },
    btn_active: {
        backgroundColor: '#7b4397',
        padding: 15,
        marginVertical: 30,
        marginHorizontal: 10,
        minWidth: 50,
        fontSize: 15,
        borderRadius: 30,
        fontWeight: '800',
        shadowColor: '#000',
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: {
            width: 5,
            height: 5,
        },
        shadowOpacity: 1,
    },
    btn_focused: {
        backgroundColor: '#7b4397',
        translateY: 4,
        alignItems: 'center',
        justifyContent: 'center',
        shadowOffset: {
            width: 1,
            height: 2,
        },
    },
    toggleButtonGroup: {
        flexDirection: 'row',
        marginBottom: 20,
    },
    toggleButton: {
        padding: 10,
        borderRadius: 4,
        marginHorizontal: 10,
        backgroundColor: '#ccc',
    },
    toggleButtonActive: {
        backgroundColor: '#7b4397',
    },
    settingsTrayContainer: {
        position: 'absolute',
        top: Platform.select({
            ios: 60,
            android: 50,
            web: 40,
            default: 20,
        }),
        left: 20,
        zIndex: 1,
      },
      settingsButton: {
        backgroundColor: 'gray',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
      },
      settingsButtonText: {
        color: 'white',
        fontSize: 24,
      },
      trayMenu: {
        backgroundColor: 'white',
        width: '100%',
        borderRadius: 10,
      },
      trayMenuItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ccc',
      },
      collectionTray: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 20,
        margin: Platform.select({
          ios: 40,
          android: 20,
          web: 40,
          default: 20,
        }),
      },
      collectionItem: {
        backgroundColor: '#E0E0E0',
        borderRadius: 50,
        padding: 20,
        margin: 10,
      },
      collectionItemActive: {
        backgroundColor: '#7b4397',
        borderRadius: 50,
        padding: 20,
        margin: 10,
      },
      loading: {
        marginTop: 20,
        marginBottom: 20,
      },
});

export default mainStyles;