name: app gate

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/**'
  workflow_dispatch:

env:
  SOURCE_DIRECTORY: ./app

jobs:
  build:
    name: app gate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up bun
      uses: oven-sh/setup-bun@v1
      with:
        version: '1.0.0'
    - name: Install dependencies
      run: bun install --production --frozen-lockfile
      working-directory: ${{ env.SOURCE_DIRECTORY }}
    - name: Build app
      run: bun build
      working-directory: ${{ env.SOURCE_DIRECTORY }}