name: app gate

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  build:
    name: app gate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: yarn install
    - name: Build app
      run: yarn build