name: app gate

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'app/**'
  workflow_dispatch:

env:
  SOURCE_DIRECTORY: ./app

jobs:
  build:
    name: app gate
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: '1.0.0'
    - name: Install dependencies
      run: bun install --production --frozen-lockfile
      working-directory: ${{ env.SOURCE_DIRECTORY }}
    - name: Build app
      run: bun run build
      working-directory: ${{ env.SOURCE_DIRECTORY }}
  build-image:
    name: app docker gate
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: app
          platforms: linux/amd64,linux/arm64
          push: false