name: app dev release
on:
  push:
    branches: ['develop']
    paths:
      - 'app/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-app
  VERSION: 1.0.0

jobs:
  build-and-push-image:
    name: app dev release
    runs-on: ubuntu-latest
    environment:
      name: develop
      url: https://dev.npole.org
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Replace variables in app.json
        uses: microsoft/variable-substitution@v1 
        with:
          files: '**/app.json'
        env:
          expo.extra.API_URL: ${{ env.API_URL }}
          expo.extra.AUTH_URL: ${{ env.AUTH_URL }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: app
          platforms: linux/amd64,linux/arm64,linux/arm64/v8
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop
